[project]
name = "sburn"
description = "A fungible token implementation following the SIP-010 standard"
authors = ["Majen"]
telemetry = false
requirements = []

[[project.requirements]]
contract_id = "ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard"  

costs_version = 2

[contracts.sburn2]
path = "contracts/sburn2.clar"
clarity_version = 2
epoch = 3.0

[network]
name = "testnet"
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"

[accounts.deployer]
mnemonic = "awkward filter safe sadness idle enrich target prize chimney foam tribe manual consider tortoise cupboard sustain admit volcano innocent chief ocean indoor phrase grow"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false

[project.deployments]
clarinet = true
testnet = { plan = "./deployments/default.testnet-plan.yaml" }
public_key = "03af3b86c9bfa2a75b63ee24d3d2c3a5b68e366360b989a5be71f86fa96adfb5f7"

[[project.wallets]]
name = "deployer"
mnemonic = "awkward filter safe sadness idle enrich target prize chimney foam tribe manual consider tortoise cupboard sustain admit volcano innocent chief ocean indoor phrase grow"
