[project]
name = "sburn"
description = "sBurn Token Implementation"
authors = ["Majen"]
telemetry = false
requirements = [
    "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.token-trait"
]

[network]
name = "testnet"
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"

[accounts.deployer]
mnemonic = "Insert seedphrase here"

[deployment]
smart-contracts = ["sburn"]
cost-estimator = "medium"

